### PR TITLE
Fixed login errors (issue #414)

### PR DESCRIPTION
**Pull request by robvdpol**

### CODE REVIEW

**Comment by jyc66** [comment]
Where did this release go?

**Comment by robvdpol** [comment]
It didn't work properly in release mode for some reason, I have to do more testing.

Anyway Race Control is not usable right now because of DRM.

**Comment by xiphiasphotography** [comment]
So it looks like the days of open API are over? "Request failed with status code Forbidden"

**Comment by speed11233** [comment]
got the same issue and problem too... started allready in FP1...  hope you can solve this out.

**Comment by speed11233** [comment]
all is solved.... thnx m8 voor het snelle reageren en oplossen ervan! toppie alweer...

**Pull request merged**
